### ISSUE TITLE
Snake game issues

### ISSUE THREAD

**Issue by craigusr** [PacktPublishing/Mastering-Qt-5#4]
I tried building/running Chapter 06 Snake in Qt 5.9.1 and 5.6.2 and got different issues. It appears to be due to the "tech preview" instability of the Qt3D Extras module.

In 5,9,1 I had to do this to get Apple.qml to load:

// Apple.qml
    PhongMaterial {
        id: material
        diffuse: "red"
    }

//    DiffuseMapMaterial {
//        id: material
//        diffuse: "qrc:/models/apple-texture.png"
//    }

In 5.6.2 just downloaded using the Qt Maintenance tool, the qt3dextras module is not found.

In both versions the grass is not displayed (black background)

**Comment by GuillaumeLazar** [comment]
Many changes seems to have been done to the Qt 3D module in 1 year. You right about the "tech preview" instability of the Qt3D module that is since Qt 5.9, inside the Qt release...

Two solutions:
1. Build Qt and Qt 3D TP module from the sources (branch 5.7). Check http://doc.qt.io/qt-5/build-sources.html and http://code.qt.io/cgit/ )
1. Update the project code source to fit the changes of Qt 3D in Qt 5.9.1

**Comment by craigusr** [comment]
Hi,

I was working on solution 2 to offer a solution but have not yet figured it out. Other similar examples seem to work.

Good book.

Thanks,
Craig


_____________________________

**Comment by GuillaumeLazar** [comment]
Please check:
 * this issue on our fork: https://github.com/neuronalmotion/Mastering-Qt-5/issues/7 
 * the new errata section: https://github.com/neuronalmotion/Mastering-Qt-5#errata

**Comment by GuillaumeLazar** [comment]
Code updated for Qt 5.10.1 in 06e3493.
